# Generated by Django 3.1.2 on 2020-11-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeta',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
