# Generated by Django 3.1.2 on 2020-11-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetas', '0002_auto_20201103_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeta',
            name='clima',
            field=models.CharField(choices=[('CO', 'Congelado'), ('TR', 'Tropical'), ('TE', 'Temperado'), ('AR', 'Árido')], max_length=200),
        ),
    ]
